### ISSUE TITLE
add to MELPA

### ISSUE THREAD

**Issue by stardiviner** [Kaali/company-glsl#1]
Hope to be installed from MELPA.

**Comment by Kaali** [comment]
Sorry, I didn't get a notification from this. Sure I can add it to MELPA if it's useful to you.

**Comment by Ell** [comment]
+1 would love to add this to a spacemacs layer I'm trying to get setup.

thanks!

**Comment by Kaali** [comment]
Sorry about not doing this. But it's happening right now from this fork: https://github.com/guidoschmidt/company-glsl
